# Generated by Django 3.2.7 on 2021-09-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='s2_corpus',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Doi', models.TextField()),
                ('YOP', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
