# Generated by Django 3.2.7 on 2021-09-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s2_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testdata',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('doi', models.TextField(blank=True, null=True)),
                ('incitations', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testdata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='s2_corpus',
        ),
    ]
